#!/bin/bash
if [[ $# -ne 1 ]]; then
echo "ARG COUNT ERROR"
exit
fi

name=$1
linkname=""
path=""
tempname=""
opt=""
newname=""
flag=0
while read str
do
path=$(echo $str | awk '{print $1}')
linkname=$(echo $str | awk '{print $2}')
tempname=$(echo $path | awk -F / '{print $5}')
if [[ $tempname == "$name" ]]; then
flag=1
echo "RESTORE "$path" ? [y/n]"
read opt < /dev/tty
fi

if test -f /home/user/.trash/$name; then
if [[ $opt == "y" ]]; then
        if [[ -d /home/user/lab4/ ]]; then
                newname=$name
                while(true) do
                        if  test  -f /home/user/lab4/$newname; then
                        echo "ENTER NEW NAME"
                        read newname < /dev/tty
                        else
                        break
                        fi
                done
        ln /home/user/.trash/$name /home/user/lab4/$newname
        else
                newname=$name
                while(true) do
                        if test -f /home/user/$newname; then
                        echo "ENTER NEW NAME"
                        read newname < /dev/tty
                        else
                        break
                        fi
                done

        echo "RESTORED TO HOME DIR"
        ln /home/user/.trash/$name /home/user/$newname
        fi
rm /home/user/.trash/$linkname
fi
else
        if [[ flag -ne 0 ]]; then
        echo "NO LINK"
        fi
fi
done < /home/user/.trash.log
if [[ flag -eq 0 ]]; then
echo "NO FILE"
fi
