#!/bin/bash
pid=0
ppid=0
sum=0
nr=0
art=0
ps aux | awk '{print $2}' | sed '1d' > temp1
touch file4
while read i
do
        if test -f "/proc/$i/status"; then

        ppid=$(cat /proc/$i/status | grep PPid | awk '{print $2}')
        sum=$(cat /proc/$i/sched | grep sum_exec_runtime | awk '{print $3}')
        nr=$(cat /proc/$i/sched | grep nr_switches | awk '{print $3}')
        art=$(echo "scale=5;$sum/$nr" | bc -l)
        pid=$i
        echo "ProcessID = "$pid" : Parent_ProcessID = "$ppid ": Average_Running_Time = "$art >> tmp
        fi
done < temp1
sort -n -k7 tmp > file4
rm temp1
rm tmp
