#!/bin/bash
pid=0
cpu=0
ni=0
test=0
pid=$(ps -au | grep proc1 | head -n 1 | awk '{print $2}')
while true
do
cpu=$(top -b -n 1 | grep proc1 | head -n 1 | awk '{print $9}')
ni=$(ps -al | grep proc1 | head -n 1 | awk '{print $8}')
if [[ $(echo "$cpu > 10.0"|bc -l ) == "1" ]]; then

ni=$(($ni+1))
renice -n $ni -p $pid
sleep 10

fi
done
